### ISSUE TITLE
importing existing YAML files

### ISSUE THREAD

**Issue by neoice** [jsok/hiera-vault#29]
has anyone done this before? the problem looks tricky enough for me to look around before I implement a solution myself.

**Comment by jsok** [comment]
This plugin is a read-only consumer of vault. If you are talking about asking `hiera-vault` to write secrets specified in a YAML file into vault, then hiera in general isn't the answer.

**Comment by neoice** [comment]
I have existing hiera.yaml I want to put into Vault so I can use this plugin. not a feature of hiera (nor should it be), but would be a useful tool to complement this project.

I'll go write one myself I guess :/

**Comment by ripclawffb** [comment]
I've started writing a puppet/type provider to write secrets into vault. I just need to figure out why I'm getting an SSL cert error even though I have valid certs. My plan is to merge it into to jsok/puppet-vault once I get it working. There's also a function I wrote to read secrets from vault and that one works fine. Check it out on my Github page.

**Comment by neoice** [comment]
writing secret data to plaintext (or hiera-eyaml) so puppet can write that secret data to an encrypted secret store...

https://www.youtube.com/watch?v=ussCHoQttyQ

**Comment by ripclawffb** [comment]
I was planning to use it to have puppet generate random secrets and populate vault so then those secrets can be used to create and set secrets on service accounts. No passwords are stored in hiera or manifests except for an authentication token that is encrypted.

**Comment by neoice** [comment]
I'll go read the code more in-depth.
