### ISSUE TITLE
VAULT_TOKEN is not being used when :token: removed from hiera config

### ISSUE THREAD

**Issue by salhadef** [jsok/hiera-vault#5]
I'm probably missing something since I'm new to the vault world...

But I had to add an IF check to line 18 to get the VAULT_TOKEN env to work:

> config.token = @config[:token] _if @config[:token]_

I'm also not a Ruby programmer.

**Comment by jsok** [comment]
Hi @salhadef thanks for the report.

Can you give a little more info about how you are setting the env var and invoking hiera and/or puppet?

**Comment by salhadef** [comment]
export VAULT_TOKEN="..."
puppet apply default.pp

**Comment by bluecmd** [comment]
As @sethvargo discovered in https://github.com/hashicorp/vault-ruby/issues/45 this also prevents reading of the token from disk, which would be a nice feature.

**Comment by jsok** [comment]
Merged #6 and released v0.1.4. @salhadef let me know if this fixes your issue. Thanks!

**Comment by salhadef** [comment]
Sorry for the late response.  Sadly we moved to a different design and didn't need this code.
